name: gruene-aktionen
type: generic
docroot: ""
php_version: ""
webserver_type: generic
database:
  type: postgres
  version: "16"
nodejs_version: "22"
web_extra_exposed_ports:
  - name: nextjs
    container_port: 3000
    http_port: 3000
    https_port: 3001
hooks:
  post-start:
    - exec: "npm install"
    - exec: "npx prisma generate"
